[[redirects]]
  from = "/api/*"
  to = "https://your-vercel-backend.vercel.app/api/:splat"
  status = 200
  force = true

[build]
  publish = "."
  
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

